name: Lint and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.19
          cache: npm

      - name: Install dependencies
        run: npm install --frozen-lockfile

      - name: Run lint check 
        run: npm run lint
        continue-on-error: true

      - name: Run tests
        run: npm run test